### ISSUE TITLE
verify OpenGL::Modern as replacement for OpenGL::Glew in app-shadertoy

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-Modern#1]
OpenGL::Modern should be a complete replacement for OpenGL::Glew in app-shadertoy since it was developed from that code base.  We need to verify that it supports all needed features so that we can consolidate development on OpenGL::Modern here to be sure any needed functionality for app-shadertoy is included and/or maintained as development continues.

**Comment by Corion** [comment]
At first glance / run, this looks quite well - nothing seems to be missing after renaming ::Glew to ::Modern.

I'm a bit unsure about what should happen with the routines in OpenGL::Glew::Helpers, as they are somewhat hacky and/or duplicate functionality that I think is present in OpenGL.pm already (the *_p functions). I'll look into that once more once I get back online.

This is really great, thanks for your work!
-max

**Comment by devel-chm** [comment]
Per mailing list discussions, the current plan is

- OpenGL::Glew::Helpers becomes an un-indexed OpenGL::Modern::API::Utils module to document the binding implementation details for users.  This can be updated as the actual implementation converges.
- OpenGL::Shader::OpenGL4 becomes OpenGL::Modern::Shader (combining with OpenGL::Shader)
- OpenGL::Texture becomes OpenGL::Modern::Texture or Image (combining with OpenGL::Image)
- Initial bindings to be very similar to C API ones but smarter about argument handling (e.g. the default would be that glXX() could dispatch to the appropriate glXX_c(), glXX_p(), glXX_s(), ... or whatever.

As always, still looking for feedback.

**Comment by devel-chm** [comment]
@Corion: Does the CPAN release work with app-shadertoy?  Since app-shadertoy needs to stay in sync with OpenGL::Modern it might be useful for use to have some sort of automated testing so you'll know if something breaks for you.  I don't know if you can do something like run tests when a new version of OpenGL::Modern gets pushed?

**Comment by Corion** [comment]
Just ealier today everything worked for me. I'll look at setting up some automated testing, but for now I think we can close this ticket

Am 18. Dezember 2016 22:38:41 MEZ, schrieb devel-chm <notifications@github.com>:
>@Corion: Does the CPAN release work with app-shadertoy?  Since
>app-shadertoy needs to stay in sync with OpenGL::Modern it might be
>useful for use to have some sort of automated testing so you'll know if
>something breaks for you.  I don't know if you can do something like
>run tests when a new version of OpenGL::Modern gets pushed?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/devel-chm/OpenGL-Modern/issues/1#issuecomment-267848727

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
