### ISSUE TITLE
Fix Travis-CI configuration

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-Modern#21]
I've enabled Travis-CI for OpenGL::Modern but the builds are failing because I don't have a valid .travis.yml configuration file.  Ideally this would be configured to work for both linux and darwin but I would be happy if just linux was working.

**Comment by wchristian** [comment]
Try @Corion's file: https://github.com/Corion/OpenGL-Modern/blob/master/.travis.yml

**Comment by wchristian** [comment]
Fixed travis up a bit.

OSX still has warnings in the make phase: https://travis-ci.org/devel-chm/OpenGL-Modern/jobs/200869959#L1943

And runtime errors when trying stuff in the tests: https://travis-ci.org/devel-chm/OpenGL-Modern/jobs/200869959#L2021

I dunno how to fix that, but i added linux and kicked off another run to see if it can succeed there.

**Comment by wchristian** [comment]
And it PASSes on two travis ubuntus: https://travis-ci.org/devel-chm/OpenGL-Modern/builds/200874031

**Comment by devel-chm** [comment]
Nice progress.  We're live with OpenGL::Modern 0.02

**Comment by wchristian** [comment]
I noticed. :)

Do you want to remove the OSX travis runs for now?

**Comment by devel-chm** [comment]
Yes, please.  We can sort it out when we get a live MacOSX user/developer.

**Comment by wchristian** [comment]
Alright, this is done then, and i updated the readme to include the travis banner.
