### ISSUE TITLE
xs constant functions are unnecessarily slow

### ISSUE THREAD

**Issue by wchristian** [Perl-GPU/OpenGL-Modern#26]
```perl
use 5.010;
use strictures;
use Time::HiRes 'time';
use OpenGL::Modern 'GL_TEXTURE_INDEX_SIZE_EXT';

sub GL_TEXTURE_INDEX_SIZE_EXTp();

eval "
    sub GL_TEXTURE_INDEX_SIZE_EXTp() { " . ( 1 + GL_TEXTURE_INDEX_SIZE_EXT ) . " };
    1;
" or die $@;

sub GL_TEXTURE_INDEX_SIZE_EXTc() { 32885 }

BEGIN {
    no strict 'refs';
    my $num = 3 + GL_TEXTURE_INDEX_SIZE_EXT;
    *{ __PACKAGE__ . "::GL_TEXTURE_INDEX_SIZE_EXTnostrict" } = sub () { $num };
}

BEGIN {
    require constant;
    constant->import( GL_TEXTURE_INDEX_SIZE_EXTimport => 4 + GL_TEXTURE_INDEX_SIZE_EXT );
}

my $c = GL_TEXTURE_INDEX_SIZE_EXT;
$c = GL_TEXTURE_INDEX_SIZE_EXTp;
$c = GL_TEXTURE_INDEX_SIZE_EXTc;
$c = GL_TEXTURE_INDEX_SIZE_EXTnostrict;
$c = GL_TEXTURE_INDEX_SIZE_EXTimport;
run();

sub run {
    my $start = time;
    for ( 1 .. 1_000_000 ) {
        $c = GL_TEXTURE_INDEX_SIZE_EXT;
    }
    say time - $start;
    $start = time;
    for ( 1 .. 1_000_000 ) {
        $c = GL_TEXTURE_INDEX_SIZE_EXTp;
    }
    say time - $start;
    $start = time;
    for ( 1 .. 1_000_000 ) {
        $c = GL_TEXTURE_INDEX_SIZE_EXTc;
    }
    say time - $start;
    $start = time;
    for ( 1 .. 1_000_000 ) {
        $c = GL_TEXTURE_INDEX_SIZE_EXTnostrict;
    }
    say time - $start;
    $start = time;
    for ( 1 .. 1_000_000 ) {
        $c = GL_TEXTURE_INDEX_SIZE_EXTimport;
    }
    say time - $start;
}

__END__

d:\cpan\OpenGL>perl benchl.pl
0.296859979629517
0.135179996490479
0.0827581882476807
0.0824580192565918
0.0822370052337646
```

**Comment by wchristian** [comment]
Throwing out the whole AutoLoader bit and replacing the end of OpenGL.pm with this seems to fix the problem. Dunno if it has any traps.

```perl


require XSLoader;
XSLoader::load( 'OpenGL::Modern', $XS_VERSION );

for my $constname ( OpenGL::Modern::NameLists::MakefileAll::makefile_all ) {
    my ( $error, $val ) = constant( $constname );
    croak $error if $error;
    no strict 'refs';
    *$constname = sub () { $val };
}
```

Total runtime of the latter section is 0.03 seconds on my system, which should be acceptable.

**Comment by devel-chm** [comment]
Nice to know we can optimize further.  I thought the AUTOLOAD eventually did the same thing as your fix.  Why doesn't it end up being a constant function at the end as your examples show perform better.

**Comment by devel-chm** [comment]
I changed the AUTOLOAD routine to add a () prototype to the routine returned,
`*$AUTOLOAD = sub () { $val };` and the result was that the AUTOLOAD variation
is now less about 2X slower compared to 4X originally.  I get the following warning
so maybe we could improve on this as well:

> Prototype mismatch: sub OpenGL::Modern::GL_TEXTURE_INDEX_SIZE_EXT: none vs () at /cygdrive/c/Perl/git/OpenGL-Modern/blib/lib/OpenGL/Modern.pm line 79.
0.0651059150695801
0.0627658367156982
0.0374469757080078
0.0373899936676025
0.0375781059265137

Now if we can just figure out why we're still not at the 0.038sec.

**Comment by wchristian** [comment]
There's no way to get around that.

() triggers two optimizations: The first is an optimization for inside the function to skip setting up @_. This is the one you managed to trigger there, which is why it got a little faster. The second one is *value inlining*, which completely removes the call, and what OpenGL.pm wants. However while the first one is only dependent on the code of the function at declaration, the second one can only be done inside compile time.

This means that any kind of autoloading will not allow inlining to happen, as the declaration of the function happens after BEGIN of the module in question is already done.

We need to with the snippet i've shown above, or our constants will never be constants.

**Comment by devel-chm** [comment]
It is good to know that we can optimize when needed.  I think with the additional prototype, the AUTOLOAD code is fast enough for the base OpenGL::Modern implementation and, I think, requires less memory as the subs are defined only for the constants actually needed.

This actually leads to a thought I had to have something like OpenGL::Modern::Constants that could provide *real* constants as both subs and readonly scalars for ease of interpolation in strings.

**Comment by wchristian** [comment]
If memory is your reason then sticking to Autoloader is pointless. The pre-declaration version uses 10.5MB, the AutoLoader version uses 9.4MB. For apps that can expect to run into the 100s of MBs and have hard realtime requirements, any speed saving is valuable enough to pay a constant cost of 1MB per process for.

**Comment by wchristian** [comment]
Suggestion via mst: Have OpenGL accept an option like `use OpenGL -lazy_constants;`, which causes the constants to be loaded from an autoloader-driven module, and otherwise it loads them from a predeclaring one.

We're also discussing a possibility to use Variable::Magic.
