### ISSUE TITLE
test 02 fails on win32

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-Modern#37]
Thanks to AS Perl, we have a build log of the test failure of OpenGL::Modern for some win32 platforms.  It appears that things are going alright...we just need to make things contingent on whether there is a sufficient version of OpenGL for the functionality used.

> dmake test TEST_VERBOSE=1
"C:\Perl64-5.20\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(1, 'blib\lib', 'blib\arch')" t/*.t
t/00_basic.t ............... 
1..3
ok 1 - use OpenGL::Modern;
ok 2 - The expected constants get exported
ok 3 - Function glClear gets exported upon request
ok
t/01_context.t ............. 
1..3
ok 1 - glewCreateContext
ok 2 - glewInit
ok 3 - GL_VERSION
> \# We got OpenGL version 1.1.0
ok
glCreateShader not available on this machine at t/02_glGetShaderInfoLog.t line 11.
> \# Looks like your test exited with 255 before it could output anything.
t/02_glGetShaderInfoLog.t .. 
1..2
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests 
t/0999_tidy.t .............. 
ok 1
1..1
ok

> Test Summary Report
> \-------------------
> t/02_glGetShaderInfoLog.t (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 2 tests but ran 0.
> Files=4, Tests=7,  2 wallclock secs ( 0.06 usr +  0.02 sys =  0.08 CPU)
> Result: FAIL

**Comment by wchristian** [comment]
OpenGL version 1.1.0 doesn't have glCreateShader.
