### ISSUE TITLE
Add Devel::CheckLib to check to OpenGL and GLU

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-Modern#39]
If we do a quick check for the includes and libraries, we can handle them missing better, at least in the error reporting for CPAN testers.

**Comment by devel-chm** [comment]
This would be a "nice to have" but the current test reports from CPAN Testers make it pretty clear that the problem is that the needed include files are not present.

**Comment by wchristian** [comment]
Thanks for the reminder on this, threw the necessary code together.
