### ISSUE TITLE
xs_buffer API changed?

### ISSUE THREAD

**Issue by dk** [Perl-GPU/OpenGL-Modern#55]
Hello,

I'm still trying to make the shadertoy working, but it seems that there are not a lot of coherent effort going on. There's that bug which I'm not sure how to fix correctly:

Argument "\0\0\0\0\0\0\0\0" isn't numeric in subroutine entry at lib/OpenGL/Shader/OpenGL4.pm at line 154. 

The line is

glGetShaderiv_c( ... , xs_buffer( $ok, 8))

But I'm confused - is it that xs_buffer supposed to return an PTR2IV(SvPV($ok)) here, or glGetShaderiv_c() should extract it from $ok, or it is the missing glGetShaderiv_p that needs to be used instead?

That looks like a trivial bug, but it would be nice if we could somehow make an effort to bring the two projects to a status that is not a nightmare to install.

Dmitry

**Comment by wchristian** [comment]
I don't have it all in memory right now, but xs_buffer underwent some changes because its original form does not work in all Perl versions: https://github.com/devel-chm/OpenGL-Modern/issues/16

**Comment by devel-chm** [comment]
The latest incarnation of xs_buffer and such documentation as we have would be in the pod and source for the OpenGL::Modern::Helpers.  Also in OpenGL::Modern::Helpers are some implementations of some routines "_p" variants compliments of Mithaldu.

Work is underway to implement native XS routines for the various OpenGL API functions but you should be able to use the current OpenGL::Modern to get the job done but things will continue to evolve so I can't promise that things won't still need to be fixed until the real XS bindings are done.

At the moment, I've documented the interfaces for what I've called the "priority" routines which are basically the set of routines used by Mithaldu, Corian, PDL, and a couple of others.  I'm starting to do some rough implementations for XS from that and extracting the patterns needed for automated code generation from those first implementations.

Once a first version is done, then I would like to implement automatic code generation from the function signatures extracted from the GLEW headers.

**Comment by mohawk2** [comment]
Since the shadertoy works beautifully, I believe this issue can be closed, so I am doing so.
