### ISSUE TITLE
Transfer to Perl-GPU

### ISSUE THREAD

**Issue by zmughal** [Perl-GPU/OpenGL-Modern#63]
@devel-chm, could you transfer this repository to @Perl-GPU?

The PAUSE permissions for this are already set up. I just sent an invite to @Perl-GPU so you should be able to accept that and transfer the repo.

**Comment by zmughal** [comment]
It would also be useful if you could transfer the other repos as well:

List:

- <https://github.com/devel-chm/OpenGL-GLUT>
- <https://github.com/devel-chm/OpenGL-GLFW>
- <https://github.com/devel-chm/OpenGL-GLU>
- <https://github.com/devel-chm/OpenGL-Modern>
- <https://github.com/devel-chm/Alien-GLFW>
- <https://github.com/devel-chm/OpenGL-Array>

**Comment by devel-chm** [comment]
How do I do the transfer?  It would be nice to see OpenGL progress in perl again....

**Comment by zmughal** [comment]
@devel-chm, there is more info here <https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account>.

There is also a way to do so for several repos at once which I have used in the past <https://github.com/jdbean/github-api-bulk-transfer>.

Let me know if there are any issues.

**Comment by devel-chm** [comment]
I think the fork of the repository is blocking the transfer.  This is the message I got on trying to transfer to Perl-GPU:  "Perl-GPU already has a repository in the devel-chm/OpenGL-GLFW network"

**Comment by zmughal** [comment]
I have transferred them elsewhere for now. If you have the `gh` command, you can run:

```shell
echo '{ "new_owner": "Perl-GPU" }' > Perl-GPU-transfer.json;
xargs -I{} gh api -X POST '/repos/{}/transfer' --input Perl-GPU-transfer.json <<EOF
devel-chm/OpenGL-GLUT
devel-chm/OpenGL-GLFW
devel-chm/OpenGL-GLU
devel-chm/OpenGL-Modern
devel-chm/Alien-GLFW
devel-chm/OpenGL-Array
EOF
```

to transfer them in one go (does a similar thing to that the script I linked does --- see the API here <https://docs.github.com/en/rest/reference/repos#transfer-a-repository>).

**Comment by devel-chm** [comment]
Went through this time.  They are processing now.

**Comment by zmughal** [comment]
Great! Thank you @devel-chm.

I've pushed the updates from the forks (only OpenGL-GLUT). Now I plan to add cross-platform CI builds (same as with PDLPorters).
